# Generated by Django 5.2.17 on 2026-10-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('crack', '裂纹检测'), ('workpiece', '工件识别')], max_length=20, verbose_name='检测任务')),
                ('source', models.CharField(choices=[('upload', '本地上传'), ('dataset', '内置数据集')], default='upload', max_length=20, verbose_name='图片来源')),
                ('input_name', models.CharField(blank=True, max_length=255, verbose_name='输入名称')),
                ('input_image', models.FileField(blank=True, upload_to='vision/inputs/%Y%m%d/', verbose_name='输入图片')),
                ('result_image', models.FileField(blank=True, upload_to='vision/results/%Y%m%d/', verbose_name='结果图片')),
                ('verdict', models.CharField(blank=True, max_length=32, verbose_name='判定结果')),
                ('object_count', models.PositiveIntegerField(default=0, verbose_name='目标数量')),
                ('elapsed_ms', models.FloatField(default=0, verbose_name='耗时(毫秒)')),
                ('detected_objects', models.JSONField(blank=True, default=list, verbose_name='检测目标')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='算法参数')),
                ('metrics', models.JSONField(blank=True, default=dict, verbose_name='扩展指标')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '视觉检测记录',
                'verbose_name_plural': '视觉检测记录',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task_type', 'created_at'], name='Manufacturi_task_ty_3a71f6_idx'), models.Index(fields=['verdict'], name='Manufacturi_verdict_46bd48_idx')],
            },
        ),
    ]
